name: rhythora
description: "The best Music Player"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Audio
  just_audio: ^0.9.42
  audio_session: ^0.1.18
  just_audio_background: ^0.0.1-beta.17
  
  # Media Query
  on_audio_query: ^2.9.0
  permission_handler: ^11.3.1
  
  # Storage & Data
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # Utilities
  package_info_plus: ^8.0.0
  share_plus: ^7.2.1
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1  

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/audio/demo.mp3
    - assets/images/default_album_art.png
    - assets/images/rhythora_logo.png

flutter_launcher_icons:
  android: true
  ios: false

  # Single image for both legacy + adaptive foreground
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#0f0f23"
  adaptive_icon_foreground: "assets/app_icon.png"

  remove_alpha_ios: true
